# NLP

In [1]:
import pandas as pd

In [2]:
df =pd.read_csv("spam_mail.csv")

In [3]:
df.head()   # first 5

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0

In [4]:
df.tail() # last 5

,Unnamed: 0,label,text,label_num
5166,1518,ham,Subject: put the 10 on the ft\r\nthe transport...,0
5167,404,ham,Subject: 3 / 4 / 2000 and following noms\r\nhp...,0
5168,2933,ham,Subject: calpine daily gas nomination\r\n>\r\n...,0
5169,1409,ham,Subject: industrial worksheets for august 2000...,0
5170,4807,spam,Subject: important online banking alert\r\ndea...,1

In [5]:
df.shape

(5171, 4)

In [6]:
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [7]:
df = df [["label" , "text"]]

In [8]:
df.head()

  label                                               text
0   ham  Subject: enron methanol ; meter # : 988291\r\n...
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...
3  spam  Subject: photoshop , windows , office . cheap ...
4   ham  Subject: re : indian springs\r\nthis deal is t...

In [9]:
df.rename(columns={"label" :"Label" ,"text":"message" }, inplace = True)

In [10]:
df.head(2)

  Label                                            message
0   ham  Subject: enron methanol ; meter # : 988291\r\n...
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...

In [11]:
df.isnull().sum()

Label      0
message    0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(178)

In [13]:
df = df.drop_duplicates()

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
print(f"Spam mesage: {(df["Label"] == "spam").sum()} ")

Spam mesage: 1462

In [16]:
print(f"Spam mesage: {(df["Label"] == "ham").sum()} ")

Spam mesage: 3531

In [17]:
print("FREE entery NOW ".lower())

free entery now

In [18]:
df["message"] = df["message"].str.lower()

In [19]:
df.head()

  Label                                            message
0   ham  subject: enron methanol ; meter # : 988291\r\n...
1   ham  subject: hpl nom for january 9 , 2001\r\n( see...
2   ham  subject: neon retreat\r\nho ho ho , we ' re ar...
3  spam  subject: photoshop , windows , office . cheap ...
4   ham  subject: re : indian springs\r\nthis deal is t...

In [20]:
import re

In [21]:
example = "Free entry 2 a walk fff text 8888"

In [22]:
example_clean = re.sub(r"[^a-z\s]" , "" , example)

In [23]:
print(example_clean)

ree entry  a walk fff text

In [24]:
df["message"] = df["message"].apply( lambda x: re.sub(r'[^a-z\s]' , '' , x))

In [25]:
df.head()

  Label                                            message
0   ham  subject enron methanol  meter   \r\nthis is a ...
1   ham  subject hpl nom for january   \r\n see attache...
2   ham  subject neon retreat\r\nho ho ho  we  re aroun...
3  spam  subject photoshop  windows  office  cheap  mai...
4   ham  subject re  indian springs\r\nthis deal is to ...

# nltk

In [26]:
import nltk

In [27]:
nltk.download("punkt")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hites\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [28]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hites\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [29]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hites\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [30]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hites\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [31]:
from nltk.tokenize import word_tokenize

sample = " helloo all how are you doing todY"

sample_token = word_tokenize(sample)

sample_token

['helloo', 'all', 'how', 'are', 'you', 'doing', 'todY']

In [32]:
from nltk.corpus import stopwords

stopwords  = set(stopwords.words('english'))

df['message'] = df['message'].apply(lambda x: " ".join(
    [words for words in word_tokenize(x)
    if words not in stopwords]
))

In [33]:
print (df['message'][2])

subject neon retreat ho ho ho around wonderful time year neon leaders retreat time know time year extremely hectic tough think anything past holidays life go past week december january like think minute calender handed beginning fall semester retreat scheduled weekend january youth ministers conference brad dustin connected week going change date following weekend january comes part need think think agree important us get together time recharge batteries get far spring semester lot trouble difficult us get away without kids etc brad came potential alternative get together weekend let know prefer first option would retreat similar done past several years year could go heartland country inn www com outside brenham nice place bedroom bedroom house side side country real relaxing also close brenham one hour minutes golf shop antique craft stores brenham eat dinner together ranch spend time meet saturday return sunday morning like done past second option would stay houston dinner together nice restaurant dessert time visiting recharging one homes saturday evening might easier trade would much time together let decide email back would preference course available weekend democratic process prevail majority vote rule let hear soon possible preferably end weekend vote go way complaining allowed like tend great weekend great golf great fishing great shopping whatever makes happy bobby

In [ ]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer ()

df['message'] = df['message'].apply(lambda x: " ".join(
    [stemmer.stem(word) for word in x.split()]
    ))

In [41]:
print (df['message'][2])

subject neon retreat ho ho ho around wonder time year neon leader retreat time know time year extrem hectic tough think anyth past holiday life go past week decemb januari like think minut calend hand begin fall semest retreat schedul weekend januari youth minist confer brad dustin connect week go chang date follow weekend januari come part need think think agr import us get togeth time recharg batteri get far spring semest lot troubl difficult us get away without kid etc brad came potenti altern get togeth weekend let know prefer first option would retreat similar done past sever year year could go heartland countri inn www com outsid brenham nice place bedroom bedroom hou side side countri real relax also close brenham one hour minut golf shop antiqu craft store brenham eat dinner togeth ranch spend time meet saturday return sunday morn like done past second option would stay houston dinner togeth nice restaur dessert time visit recharg one home saturday even might easier trade would much time togeth let decid email back would prefer cour avail weekend democrat process prevail major vote rule let hear soon possibl prefer end weekend vote go way complain allow like tend great weekend great golf great fish great shop whatev make happi bobbi

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [43]:
x = df['message']

In [44]:
y = df['Label']

In [45]:
tfidf = TfidfVectorizer(max_features=3000)

In [51]:
X_vec = tfidf.fit_transform(x)
Y = tfidf.fit_transform(y)

In [52]:
X_vec.shape[1]

3000

In [53]:
from sklearn.model_selection import train_test_split

In [57]:
X_train , X_test , Y_train , Y_test = train_test_split(
    X_vec,
    Y,
    test_size = 0.20 ,
    random_state=42
)

In [58]:
from sklearn.naive_bayes import MultinomialNB

In [59]:
model = MultinomialNB()

In [60]:
model.fit(X_train, Y_train)

TypeError: Sparse data was passed for y, but dense data is required. Use '.toarray()' to convert to a dense numpy array.

In [61]:
Y_pred = model.predict(X_test)

NotFittedError: This MultinomialNB instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [62]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
accuracy_score = accuracy_score(Y_text , Y_pred)

NameError: name 'Y_text' is not defined

In [63]:
print(accuracy_score)

<function accuracy_score at 0x000001E97327AD40>

In [64]:
cm = confusion_matrix(Y_text , Y_pred)

cm

NameError: name 'Y_text' is not defined

In [65]:
def precit_message(message ):
    msg = message.lower()
    msg = re.sub((r"[^a-z\s]") , "" , msg)
    token = word_tokenize(msg)
    token = [w for w in token
            if w not in stopwords]
    token = [stemmer.stem(w) for w in token:
    clean_msg = " ".join(tokens)
    vec = tfidf.transform(clean_msg)
    result = model.predict(vec)[0]
    return result , prob

SyntaxError: invalid syntax (813090488.py, line 7)

In [66]:
text_msg = (
            """

            cogratulation click on the link bro  for wining the money urgent click now
           
            """ 
    )

In [67]:
precit_message(text_msg)

NameError: name 'precit_message' is not defined